dynamic_unicycle_hero:
  robot: dynamic_unicycle
  description: Extracted exactly from image.
  start_state:
  - 2.0
  - 5.0
  - 0.0
  - 0.0
  goal:
  - 16.0
  - 5.0
  obstacles:
  - center:
    - 8.84
    - 11.01
    radius: 0.87
  - center:
    - 12.6
    - 10.99
    radius: 0.63
  - center:
    - 7.54
    - 10.17
    radius: 0.89
  - center:
    - 5.63
    - 10.61
    radius: 0.51
  - center:
    - 11.13
    - 10.03
    radius: 0.84
  - center:
    - 13.54
    - 9.65
    radius: 0.87
  - center:
    - 10.36
    - 8.79
    radius: 0.79
  - center:
    - 12.66
    - 7.92
    radius: 0.87
  - center:
    - 10.41
    - 7.76
    radius: 0.41
  - center:
    - 7.7
    - 7.81
    radius: 0.73
  - center:
    - 11.73
    - 7.13
    radius: 0.63
  - center:
    - 13.35
    - 6.61
    radius: 0.68
  - center:
    - 9.81
    - 6.49
    radius: 0.95
  - center:
    - 11.38
    - 6.35
    radius: 0.33
  - center:
    - 11.81
    - 5.23
    radius: 0.87
  - center:
    - 12.94
    - 5.87
    radius: 0.37
  - center:
    - 6.35
    - 5.48
    radius: 0.56
  - center:
    - 13.34
    - 4.84
    radius: 0.85
  - center:
    - 5.63
    - 5.06
    radius: 0.47
  - center:
    - 6.99
    - 4.15
    radius: 0.88
  - center:
    - 8.7
    - 3.17
    radius: 0.87
  - center:
    - 5.66
    - 3.94
    radius: 0.47
  - center:
    - 5.7
    - 2.41
    radius: 0.65
  - center:
    - 8.17
    - 2.19
    radius: 0.4
  - center:
    - 12.0
    - 1.72
    radius: 0.52
  - center:
    - 6.64
    - 1.2
    radius: 0.8
  - center:
    - 13.34
    - 0.93
    radius: 0.77
  - center:
    - 9.42
    - 0.49
    radius: 0.61
  - center:
    - 11.42
    - 0.32
    radius: 0.67
  - center:
    - 4.51
    - 0.28
    radius: 0.57
  - center:
    - 10.28
    - -0.41
    radius: 0.8
  - center:
    - 13.01
    - -0.36
    radius: 0.76
  - center:
    - 5.49
    - -0.79
    radius: 0.97
  - center:
    - 6.78
    - -0.34
    radius: 0.7
  - center:
    - 4.09
    - -0.71
    radius: 0.31
mobile_arm_scenario:
  robot: mobile_arm
  description: A highly complex retraction challenge for the mobile arm.
  start_state:
  - 2.0
  - 5.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  goal:
  - 16.0
  - 5.0
  obstacles:
  - center:
    - 4.0
    - 9.0
    radius: 1.5
  - center:
    - 8.0
    - 8.5
    radius: 1.5
  - center:
    - 12.0
    - 9.0
    radius: 1.5
  - center:
    - 4.0
    - 1.0
    radius: 1.5
  - center:
    - 8.0
    - 1.5
    radius: 1.5
  - center:
    - 12.0
    - 1.0
    radius: 1.5
  - center:
    - 6.0
    - 6.5
    radius: 0.5
  - center:
    - 6.0
    - 3.5
    radius: 0.5
  - center:
    - 10.0
    - 6.5
    radius: 0.5
  - center:
    - 10.0
    - 3.5
    radius: 0.5
  - center:
    - 7.0
    - 4.0
    radius: 0.3
  - center:
    - 11.0
    - 6.0
    radius: 0.3
  - center:
    - 13.2
    - 5.0
    radius: 0.52
  - center:
    - 13.2
    - 5.8
    radius: 0.5
  - center:
    - 13.2
    - 4.2
    radius: 0.5
planar_quadrotor_hero:
  robot: planar_quadrotor
  description: Extracted exactly from image.
  start_state:
  - 2.0
  - 5.0
  - 0.0
  - 0.0
  - 0.0
  goal:
  - 16.0
  - 5.0
  obstacles:
  - center:
    - 7.13
    - 11.46
    radius: 0.77
  - center:
    - 5.46
    - 10.75
    radius: 0.82
  - center:
    - 12.79
    - 10.23
    radius: 0.82
  - center:
    - 7.75
    - 9.5
    radius: 1.14
  - center:
    - 5.62
    - 8.96
    radius: 0.98
  - center:
    - 12.92
    - 9.18
    radius: 1.0
  - center:
    - 9.87
    - 8.21
    radius: 0.92
  - center:
    - 4.2
    - 7.64
    radius: 0.65
  - center:
    - 14.0
    - 8.32
    radius: 0.48
  - center:
    - 8.29
    - 7.03
    radius: 1.05
  - center:
    - 11.51
    - 5.14
    radius: 1.03
  - center:
    - 6.35
    - 5.56
    radius: 0.66
  - center:
    - 13.39
    - 4.06
    radius: 1.16
  - center:
    - 10.08
    - 3.84
    radius: 0.88
  - center:
    - 5.45
    - 4.19
    radius: 0.99
  - center:
    - 11.3
    - 4.05
    radius: 0.83
  - center:
    - 5.96
    - 4.5
    radius: 1.09
  - center:
    - 9.07
    - 2.88
    radius: 0.79
  - center:
    - 10.18
    - 3.18
    radius: 0.25
  - center:
    - 10.82
    - 2.64
    radius: 0.51
  - center:
    - 4.24
    - 0.93
    radius: 1.08
  - center:
    - 5.61
    - 1.24
    radius: 0.56
  - center:
    - 10.3
    - 2.25
    radius: 0.25
  - center:
    - 11.8
    - 1.76
    radius: 0.72
  - center:
    - 8.04
    - 1.67
    radius: 0.53
  - center:
    - 10.29
    - 0.72
    radius: 0.87
  - center:
    - 7.24
    - 0.62
    radius: 0.88
  - center:
    - 8.96
    - 0.63
    radius: 0.86
  - center:
    - 6.03
    - 0.2
    radius: 0.57
  - center:
    - 12.18
    - -0.43
    radius: 0.93
single_integrator_hero:
  robot: single_integrator
  description: Extracted exactly from image.
  start_state:
  - 2.0
  - 5.0
  goal:
  - 16.0
  - 5.0
  obstacles:
  - center:
    - 12.25
    - 10.91
    radius: 0.76
  - center:
    - 5.97
    - 10.48
    radius: 0.62
  - center:
    - 14.31
    - 10.29
    radius: 0.33
  - center:
    - 8.28
    - 10.06
    radius: 0.38
  - center:
    - 11.39
    - 9.98
    radius: 0.41
  - center:
    - 12.86
    - 9.79
    radius: 0.32
  - center:
    - 8.94
    - 9.52
    radius: 0.48
  - center:
    - 14.27
    - 9.4
    radius: 0.64
  - center:
    - 10.66
    - 9.61
    radius: 0.7
  - center:
    - 5.51
    - 9.74
    radius: 0.44
  - center:
    - 4.49
    - 9.02
    radius: 0.56
  - center:
    - 13.21
    - 9.29
    radius: 0.3
  - center:
    - 12.19
    - 8.64
    radius: 0.78
  - center:
    - 9.64
    - 8.78
    radius: 0.65
  - center:
    - 5.61
    - 8.61
    radius: 0.63
  - center:
    - 11.37
    - 8.78
    radius: 0.31
  - center:
    - 6.38
    - 8.39
    radius: 0.38
  - center:
    - 13.58
    - 8.11
    radius: 0.66
  - center:
    - 10.65
    - 7.92
    radius: 0.7
  - center:
    - 4.52
    - 7.78
    radius: 0.29
  - center:
    - 3.68
    - 6.77
    radius: 0.56
  - center:
    - 11.81
    - 6.32
    radius: 0.7
  - center:
    - 5.13
    - 6.29
    radius: 0.71
  - center:
    - 13.78
    - 6.34
    radius: 0.56
  - center:
    - 9.5
    - 6.23
    radius: 0.54
  - center:
    - 12.75
    - 5.92
    radius: 0.46
  - center:
    - 8.81
    - 5.84
    radius: 0.33
  - center:
    - 3.54
    - 5.63
    radius: 0.45
  - center:
    - 7.31
    - 5.34
    radius: 0.34
  - center:
    - 4.46
    - 5.26
    radius: 0.38
  - center:
    - 6.01
    - 4.97
    radius: 0.41
  - center:
    - 8.11
    - 4.89
    radius: 0.49
  - center:
    - 11.4
    - 5.0
    radius: 0.35
  - center:
    - 10.27
    - 4.54
    radius: 0.64
  - center:
    - 13.78
    - 4.69
    radius: 0.51
  - center:
    - 3.51
    - 3.96
    radius: 0.31
  - center:
    - 13.97
    - 3.86
    radius: 0.44
  - center:
    - 13.04
    - 3.4
    radius: 0.7
  - center:
    - 11.62
    - 3.53
    radius: 0.48
  - center:
    - 8.82
    - 3.09
    radius: 0.53
  - center:
    - 10.83
    - 3.09
    radius: 0.31
  - center:
    - 9.55
    - 2.82
    radius: 0.31
  - center:
    - 11.43
    - 2.61
    radius: 0.34
  - center:
    - 10.7
    - 2.38
    radius: 0.37
  - center:
    - 13.21
    - 2.42
    radius: 0.4
  - center:
    - 7.33
    - 1.85
    radius: 0.49
  - center:
    - 3.48
    - 1.84
    radius: 0.5
  - center:
    - 4.26
    - 1.73
    radius: 0.41
  - center:
    - 11.46
    - 1.51
    radius: 0.29
  - center:
    - 8.11
    - 1.44
    radius: 0.35
  - center:
    - 13.84
    - 1.42
    radius: 0.23
  - center:
    - 4.76
    - 1.18
    radius: 0.42
  - center:
    - 13.45
    - 0.85
    radius: 0.44
  - center:
    - 3.98
    - 1.18
    radius: 0.32
  - center:
    - 6.74
    - 0.87
    radius: 0.4
  - center:
    - 7.6
    - 0.62
    radius: 0.7
  - center:
    - 5.74
    - 0.48
    radius: 0.58
  - center:
    - 3.75
    - 0.35
    radius: 0.36
  - center:
    - 10.45
    - 0.49
    radius: 0.51
  - center:
    - 8.55
    - -0.24
    radius: 0.78
  - center:
    - 4.61
    - 0.2
    radius: 0.45
  - center:
    - 11.83
    - -0.06
    radius: 0.66
  - center:
    - 10.38
    - -0.44
    radius: 0.58
  - center:
    - 5.21
    - -0.58
    radius: 0.58
  - center:
    - 6.56
    - -0.92
    radius: 0.71
unicycle_hero:
  robot: unicycle
  description: Extracted exactly from image.
  start_state:
  - 2.0
  - 5.0
  - 0.0
  goal:
  - 16.0
  - 5.0
  obstacles:
  - center:
    - 6.14
    - 8.92
    radius: 0.62
  - center:
    - 10.54
    - 8.63
    radius: 0.68
  - center:
    - 13.73
    - 8.76
    radius: 0.36
  - center:
    - 8.24
    - 8.45
    radius: 0.44
  - center:
    - 8.92
    - 8.34
    radius: 0.34
  - center:
    - 9.62
    - 7.91
    radius: 0.21
  - center:
    - 10.71
    - 7.64
    radius: 0.46
  - center:
    - 6.58
    - 7.16
    radius: 0.54
  - center:
    - 11.65
    - 7.12
    radius: 0.69
  - center:
    - 9.71
    - 6.98
    radius: 0.64
  - center:
    - 4.91
    - 6.91
    radius: 0.56
  - center:
    - 13.52
    - 7.07
    radius: 0.36
  - center:
    - 12.94
    - 6.77
    radius: 0.38
  - center:
    - 5.77
    - 6.55
    radius: 0.59
  - center:
    - 6.47
    - 5.8
    radius: 0.69
  - center:
    - 11.66
    - 5.04
    radius: 0.66
  - center:
    - 4.41
    - 4.56
    radius: 0.72
  - center:
    - 8.07
    - 4.77
    radius: 0.35
  - center:
    - 11.26
    - 4.03
    radius: 0.48
  - center:
    - 13.57
    - 3.84
    radius: 0.58
  - center:
    - 8.85
    - 2.97
    radius: 0.56
  - center:
    - 8.05
    - 3.36
    radius: 0.25
  - center:
    - 6.89
    - 3.24
    radius: 0.35
  - center:
    - 7.54
    - 3.18
    radius: 0.25
  - center:
    - 12.61
    - 2.89
    radius: 0.67
  - center:
    - 10.87
    - 2.43
    radius: 0.7
  - center:
    - 13.61
    - 2.15
    radius: 0.66
  - center:
    - 7.12
    - 2.55
    radius: 0.26
  - center:
    - 8.14
    - 2.59
    radius: 0.1
  - center:
    - 8.07
    - 1.67
    radius: 0.74
  - center:
    - 12.5
    - 1.7
    radius: 0.36
  - center:
    - 13.77
    - 1.15
    radius: 0.63
  - center:
    - 9.63
    - 1.19
    radius: 0.46
